### ISSUE TITLE
Cannot execute run.sh

### ISSUE THREAD

**Issue by NormanDunbar** [t-paul/fritzing-dev-build#1]
Hi.

My system is Linux Mint 64 bit 21.3 (Virginia).

I've cloned your repository; executed the `build.sh` script which finished with no errors; but the `run.sh` script fails with the following errors:

```
xauth:  file /root/.Xauthority does not exist
bash: line 1: /fritzing/Fritzing: No such file or directory
```

I'm not a Docker guru, I'm afraid, but I think the command line is associating the `fritzing` directory, inside the container, with the `fritzing-app/fritzing-*.linux.*` directory, outside the container. However, in my setup, that latter directory is empty. I have confirmed this by changing the final line of the `run.sh1 script to:

```
bash -c 'xauth add $COOKIE && ls -Rl /fritzing'
```
The result is:

```
xauth:  file /root/.Xauthority does not exist
/fritzing:
total 0
```

Would you have any suggestions as to what I should do to get this working please. Thanks.

Regards,
Norman.

**Comment by NormanDunbar** [comment]
Ok, it appears I lied! The `build.sh` did fail with an error:

```
xauth:  file /root/.Xauthority does not exist
Usage: ./tools/linux_release_script/release.sh <need a version string such as '0.6.4b' (without the quotes)>
```

This was from :

```
bash -c 'xauth add $COOKIE && ./tools/linux_release_script/release.sh "$VER"'
```

where `${VER}` is 1.0.2c.


Cheers,
Norm.

**Comment by t-paul** [comment]
Updated for 1.0.3, works for me locally again.

**Comment by NormanDunbar** [comment]
Thanks. That fixed it.

Cheers,
Norm.
